// author.js — password-gated blog editor that commits to GitHub.
//
// Security model (static site, public repo, no backend):
//   * Your GitHub token is encrypted with your password using WebCrypto:
//     AES-256-GCM with a key derived via PBKDF2-SHA256 (600k iterations,
//     random 16-byte salt + 12-byte IV). The plaintext token is NEVER stored.
//   * `login` decrypts the token with your password. A wrong password makes
//     AES-GCM auth-tag verification fail, so the password *is* the key — no
//     separate password hash is kept anywhere.
//   * The encrypted blob can live only in this browser (localStorage) or, opt
//     in, be published to the repo (auth.json) for cross-device login. Even
//     published it is just ciphertext — only as safe as your password is hard.
//
// Classic script: shares global scope with app.js/content.js (h, emit, line,
// box, route, blogs, getPost, currentPath, input, …).

(function () {
  "use strict";

  const GH = {
    owner: "aPR0T0",
    repo: "aPR0T0.github.io",
    branch: "master",
    postsPath: "posts.js",
    authPath: "auth.json",
  };
  const BLOB_KEY = "author.blob";
  const PBKDF2_ITER = 600000;

  let sessionToken = null;
  let authMode = false;

  /* ---------- base64 ---------- */
  function bytesToB64(bytes) {
    let s = "";
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      s += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
    }
    return btoa(s);
  }
  function b64ToBytes(b64) {
    const bin = atob(b64);
    const a = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) a[i] = bin.charCodeAt(i);
    return a;
  }
  function strToB64(str) {
    return bytesToB64(new TextEncoder().encode(str));
  }

  /* ---------- WebCrypto ---------- */
  function hasCrypto() {
    return !!(window.crypto && window.crypto.subtle);
  }
  function requireCrypto() {
    if (hasCrypto()) return true;
    emit(line("WebCrypto unavailable — open the site over https or localhost.", "err"));
    return false;
  }
  async function deriveKey(password, salt, iter) {
    const km = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(password),
      "PBKDF2",
      false,
      ["deriveKey"]
    );
    return crypto.subtle.deriveKey(
      { name: "PBKDF2", salt, iterations: iter, hash: "SHA-256" },
      km,
      { name: "AES-GCM", length: 256 },
      false,
      ["encrypt", "decrypt"]
    );
  }
  async function encryptSecret(plaintext, password) {
    const salt = crypto.getRandomValues(new Uint8Array(16));
    const iv = crypto.getRandomValues(new Uint8Array(12));
    const key = await deriveKey(password, salt, PBKDF2_ITER);
    const ct = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv },
      key,
      new TextEncoder().encode(plaintext)
    );
    return {
      v: 1,
      alg: "AES-256-GCM",
      kdf: "PBKDF2-SHA256",
      iter: PBKDF2_ITER,
      salt: bytesToB64(salt),
      iv: bytesToB64(iv),
      ct: bytesToB64(new Uint8Array(ct)),
    };
  }
  async function decryptSecret(blob, password) {
    const key = await deriveKey(password, b64ToBytes(blob.salt), blob.iter || PBKDF2_ITER);
    const pt = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: b64ToBytes(blob.iv) },
      key,
      b64ToBytes(blob.ct)
    );
    return new TextDecoder().decode(pt);
  }

  /* ---------- GitHub Contents API ---------- */
  function ghHeaders() {
    return {
      Authorization: "Bearer " + sessionToken,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    };
  }
  async function ghGetSha(path) {
    const url = `https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${path}?ref=${GH.branch}`;
    const r = await fetch(url, { headers: ghHeaders(), cache: "no-store" });
    if (r.status === 404) return null;
    if (!r.ok) throw new Error("read " + path + " -> " + r.status);
    return (await r.json()).sha;
  }
  async function ghPut(path, contentStr, message) {
    const sha = await ghGetSha(path);
    const body = { message, content: strToB64(contentStr), branch: GH.branch };
    if (sha) body.sha = sha;
    const r = await fetch(
      `https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${path}`,
      { method: "PUT", headers: { ...ghHeaders(), "Content-Type": "application/json" }, body: JSON.stringify(body) }
    );
    if (!r.ok) {
      let msg = "";
      try { msg = (await r.json()).message; } catch (e) {}
      throw new Error("commit " + path + " -> " + r.status + (msg ? " (" + msg + ")" : ""));
    }
    return r.json();
  }

  /* ---------- posts serialization ---------- */
  const POSTS_HEADER =
    "// posts.js — blog posts data (regenerated by the in-browser editor).\n" +
    "// Plain `window.BLOG_POSTS = [...]` so it can be rewritten + committed safely.\n";
  function serializePosts() {
    return POSTS_HEADER + "window.BLOG_POSTS = " + JSON.stringify(blogs, null, 2) + ";\n";
  }

  /* ---------- small UI helpers ---------- */
  function kvList(rows) {
    return h(
      "dl",
      { class: "kv" },
      rows.flatMap(([k, v]) => [h("dt", { text: k }), h("dd", { text: v })])
    );
  }
  function askLine(label, opts) {
    const secret = !!(opts && opts.secret);
    return new Promise((resolve) => {
      const inp = h("input", {
        type: secret ? "password" : "text",
        class: "authinput",
        autocomplete: "off",
        autocapitalize: "off",
        spellcheck: "false",
      });
      const form = h("form", { class: "authform" }, [
        h("span", { class: "authlabel", text: label + ":" }),
        inp,
        h("button", { type: "submit", class: "authbtn", text: "ok" }),
      ]);
      let done = false;
      // `armed` guards against the very Enter keystroke that launched this
      // prompt from instantly submitting the still-empty field (which used to
      // read as an empty value -> "cancelled.").
      let armed = false;
      const finish = (val) => {
        if (done || !armed) return;
        done = true;
        const shown = val == null ? "(cancelled)" : secret ? "••••••••" : val;
        form.replaceWith(h("div", { class: "block" }, line(label + ": " + shown, "muted")));
        resolve(val);
        input.focus();
      };
      form.addEventListener("submit", (e) => { e.preventDefault(); finish(inp.value); });
      inp.addEventListener("keydown", (e) => {
        if (e.key === "Escape") { e.preventDefault(); finish(null); }
        else if (e.key === "Enter" && !armed) { e.preventDefault(); }
      });
      emit(form);
      // Focus + arm on a later tick, after the triggering keystroke is fully
      // processed, so it can't auto-submit this prompt.
      setTimeout(() => { inp.focus(); armed = true; }, 80);
    });
  }

  /* ---------- editor ---------- */
  function field(labelText, el) {
    return h("div", { class: "erow" }, [h("label", { class: "elabel", text: labelText }), el]);
  }
  function openEditor(post) {
    return new Promise((resolve) => {
      const isNew = !post;
      const today = new Date().toISOString().slice(0, 10);

      const slugIn = h("input", { class: "einput", value: post ? post.slug : "", placeholder: "my-post-slug", spellcheck: "false", autocapitalize: "off" });
      if (!isNew) slugIn.setAttribute("readonly", "readonly");
      const titleIn = h("input", { class: "einput", value: post ? post.title : "", placeholder: "Post title" });
      const dateIn = h("input", { class: "einput", value: post ? post.date : today, placeholder: "YYYY-MM-DD" });
      const tagsIn = h("input", { class: "einput", value: post ? (post.tags || []).join(", ") : "", placeholder: "tag1, tag2" });
      const sumIn = h("textarea", { class: "etext", rows: "2", placeholder: "One-line summary" });
      sumIn.value = post ? post.summary || "" : "";
      const bodyIn = h("textarea", { class: "etext ebig", rows: "14", placeholder: "Body (markdown). Blank line = new paragraph.\n\n## A heading\n\n**bold**, _italic_, `code`, [link](https://…)\n\n- a list item\n> a quote" });
      bodyIn.value = post ? (post.body || []).join("\n\n") : "";

      const commitBtn = h("button", { type: "button", class: "authbtn ecommit", text: isNew ? "create + commit" : "save + commit" });
      const cancelBtn = h("button", { type: "button", class: "authbtn ecancel", text: "cancel" });
      const errP = h("p", { class: "tline err eerr", style: "display:none" });

      const wrap = h("div", { class: "editor" }, [
        h("div", { class: "boxx-bar" }, [
          h("span", { class: "boxx-dot" }),
          h("span", { class: "boxx-label", text: isNew ? "new post" : "edit · " + post.slug }),
        ]),
        h("div", { class: "editor-body" }, [
          field("slug", slugIn),
          field("title", titleIn),
          field("date", dateIn),
          field("tags", tagsIn),
          field("summary", sumIn),
          field("body", bodyIn),
          errP,
          h("div", { class: "ebtns" }, [commitBtn, cancelBtn]),
          h("p", { class: "tline muted", text: "tip: markdown supported (#, **bold**, _italic_, `code`, - lists, > quote). blank line = new paragraph. Esc cancels." }),
        ]),
      ]);

      let done = false;
      const finish = (val) => {
        if (done) return;
        done = true;
        wrap.replaceWith(
          h("div", { class: "block" }, line(val ? "staged: " + val.slug : "editor closed.", "muted"))
        );
        resolve(val);
        input.focus();
      };
      const showErr = (m) => { errP.textContent = m; errP.style.display = ""; };

      cancelBtn.addEventListener("click", () => finish(null));
      commitBtn.addEventListener("click", () => {
        const slug = slugIn.value.trim().toLowerCase().replace(/[^\w-]+/g, "-").replace(/^-+|-+$/g, "");
        const title = titleIn.value.trim();
        const date = (dateIn.value.trim() || today);
        const tags = tagsIn.value.split(",").map((s) => s.trim()).filter(Boolean);
        const summary = sumIn.value.trim();
        const body = bodyIn.value.split(/\n\s*\n/).map((s) => s.trim()).filter(Boolean);
        if (!slug) return showErr("slug is required.");
        if (!title) return showErr("title is required.");
        if (!body.length) return showErr("body is required.");
        const year = parseInt(date.slice(0, 4), 10) || new Date().getFullYear();
        finish({ slug, title, date, year, tags, summary, body });
      });
      [slugIn, titleIn, dateIn, tagsIn].forEach((el) =>
        el.addEventListener("keydown", (e) => { if (e.key === "Escape") { e.preventDefault(); finish(null); } })
      );

      emit(wrap);
      // defer focus so the Enter that opened the editor isn't captured by a field
      setTimeout(() => titleIn.focus(), 60);
    });
  }

  /* ---------- commit flow ---------- */
  async function commitPosts(message) {
    emit(line("committing " + GH.postsPath + " to " + GH.owner + "/" + GH.repo + " …", "muted"));
    try {
      const res = await ghPut(GH.postsPath, serializePosts(), message);
      emit(line("committed ✓  GitHub Pages redeploys in ~1 min.", "ok2"));
      const url = res && res.commit && res.commit.html_url;
      if (url) emit(h("p", { class: "tline muted" }, ["commit: ", extLink(url, url)]));
      return true;
    } catch (e) {
      emit(line("commit failed: " + e.message, "err"));
      if (/-> 40[13]\b/.test(e.message)) {
        emit(line("→ your token can READ but not WRITE this repo.", "muted"));
        emit(line("  fix: GitHub token needs  Contents: Read and write  (not read-only),", "muted"));
        emit(line("  scoped to " + GH.owner + "/" + GH.repo + ". Then:  auth reset  →  auth setup", "muted"));
      } else {
        emit(line("your edit is still in memory — fix the token/permissions and retry.", "muted"));
      }
      return false;
    }
  }

  function ensureAuth() {
    if (authMode && sessionToken) return true;
    emit(line("locked. run: login   (first time: auth setup)", "err"));
    return false;
  }

  /* ---------- commands ---------- */
  extraCommands.auth = async (args) => {
    const sub = (args[0] || "").toLowerCase();
    if (sub === "setup") return authSetup();
    if (sub === "status") return authStatus();
    if (sub === "publish") return authPublish();
    if (sub === "reset") return authReset();
    emit(
      box("auth", [
        line("Edit + commit blog posts from the browser. Your GitHub token is", ),
        line("encrypted with your password (AES-256-GCM + PBKDF2). No plaintext, ever.", "muted"),
        kvList([
          ["auth setup", "encrypt a GitHub token with a password (one time)"],
          ["login", "unlock author mode with your password"],
          ["edit <slug>", "edit a post, then commit it"],
          ["new", "write a new post, then commit it"],
          ["auth publish", "store the encrypted blob in the repo (cross-device login)"],
          ["auth status", "show current auth state"],
          ["auth reset", "remove the encrypted blob from this browser"],
          ["logout", "lock author mode"],
        ]),
        line("Use a long passphrase + a fine-grained token scoped to ONLY this repo", "muted"),
        line("(Contents: read & write) with an expiry. The blob is only as safe as your password.", "muted"),
      ])
    );
  };

  async function authSetup() {
    if (!requireCrypto()) return;
    emit(line("Set up author mode.", "ok2"));
    emit(line("Paste a GitHub fine-grained token (Contents: read & write on this repo).", "muted"));
    const token = await askLine("github token", { secret: true });
    if (!token) return emit(line("cancelled.", "muted"));
    const pw = await askLine("new password", { secret: true });
    if (!pw) return emit(line("cancelled.", "muted"));
    const pw2 = await askLine("confirm password", { secret: true });
    if (pw !== pw2) return emit(line("passwords do not match.", "err"));
    if (pw.length < 10) emit(line("warning: short password — a longer passphrase is much safer.", "muted"));
    emit(line("encrypting (PBKDF2 " + PBKDF2_ITER.toLocaleString() + " rounds)…", "muted"));
    try {
      const blob = await encryptSecret(token, pw);
      try { localStorage.setItem(BLOB_KEY, JSON.stringify(blob)); } catch (e) {}
      sessionToken = token;
      authMode = true;
      emit(line("done. token encrypted + saved to this browser. author mode ON.", "ok2"));
      emit(line("optional: run  auth publish  to enable login from other devices.", "muted"));
      emit(line("try: new   ·   edit " + (blogs[0] ? blogs[0].slug : "<slug>"), "muted"));
    } catch (e) {
      emit(line("setup failed: " + e.message, "err"));
    }
  }

  function authStatus() {
    let hasLocal = false;
    try { hasLocal = !!localStorage.getItem(BLOB_KEY); } catch (e) {}
    emit(
      box("auth status", [
        kvList([
          ["author mode", authMode ? "ON" : "off"],
          ["encrypted blob (local)", hasLocal ? "present" : "none"],
          ["repo", GH.owner + "/" + GH.repo + " @ " + GH.branch],
          ["crypto", hasCrypto() ? "WebCrypto available" : "unavailable (needs https)"],
        ]),
      ])
    );
  }

  async function authPublish() {
    if (!ensureAuth()) return;
    let blobStr = null;
    try { blobStr = localStorage.getItem(BLOB_KEY); } catch (e) {}
    if (!blobStr) return emit(line("no local encrypted blob. run: auth setup", "err"));
    emit(line("publishing encrypted blob to " + GH.authPath + " …", "muted"));
    try {
      await ghPut(GH.authPath, blobStr + "\n", "chore: update encrypted author blob");
      emit(line("published ✓  you can now `login` on other devices with your password.", "ok2"));
      emit(line("note: auth.json is public but encrypted — safe only with a strong password.", "muted"));
    } catch (e) {
      emit(line("publish failed: " + e.message, "err"));
    }
  }

  function authReset() {
    try { localStorage.removeItem(BLOB_KEY); } catch (e) {}
    sessionToken = null;
    authMode = false;
    emit(line("local encrypted blob removed; author mode off.", "muted"));
  }

  extraCommands.login = async () => {
    if (!requireCrypto()) return;
    if (authMode) return emit(line("already logged in.", "muted"));
    let blobStr = null;
    try { blobStr = localStorage.getItem(BLOB_KEY); } catch (e) {}
    if (!blobStr) {
      try {
        const r = await fetch("./" + GH.authPath, { cache: "no-store" });
        if (r.ok) blobStr = await r.text();
      } catch (e) {}
    }
    if (!blobStr) return emit(line("no author profile on this device. run: auth setup", "err"));
    const pw = await askLine("password", { secret: true });
    if (pw == null) return emit(line("cancelled.", "muted"));
    try {
      const token = await decryptSecret(JSON.parse(blobStr), pw);
      sessionToken = token;
      authMode = true;
      emit(line("unlocked ✓ author mode ON.", "ok2"));
      emit(line("try: new   ·   edit " + (blogs[0] ? blogs[0].slug : "<slug>") + "   ·   logout", "muted"));
    } catch (e) {
      emit(line("wrong password — decryption failed.", "err"));
    }
  };

  extraCommands.logout = () => {
    sessionToken = null;
    authMode = false;
    emit(line("logged out. author mode off.", "muted"));
  };

  extraCommands.edit = async (args) => {
    if (!ensureAuth()) return;
    const slug = (args[0] || "").replace(/^\.?\/?(blogs\/)?/, "").trim().toLowerCase();
    if (!slug) return emit(line("usage: edit <slug>   (see: ls blogs)", "err"));
    const post = getPost(slug);
    if (!post) return emit(line('no post "' + slug + '". try: ls blogs', "err"));
    const data = await openEditor(post);
    if (!data) return emit(line("edit cancelled.", "muted"));
    delete data.slug; // slug is immutable on edit
    Object.assign(post, data); // mutate in place (same ref as window.BLOG_POSTS)
    const ok = await commitPosts("blog: edit " + post.slug);
    if (ok) emit(h("p", { class: "tline muted" }, ["view: ", internalLink("blogs/" + post.slug, "./blogs/" + post.slug)]));
  };

  extraCommands.new = async () => {
    if (!ensureAuth()) return;
    const data = await openEditor(null);
    if (!data) return emit(line("new post cancelled.", "muted"));
    if (getPost(data.slug)) return emit(line('a post with slug "' + data.slug + '" already exists.', "err"));
    blogs.unshift(data);
    const ok = await commitPosts("blog: add " + data.slug);
    if (ok) emit(h("p", { class: "tline muted" }, ["view: ", internalLink("blogs/" + data.slug, "./blogs/" + data.slug)]));
  };

  // aliases
  extraCommands.author = extraCommands.auth;
})();
