// posts.js — blog posts data (regenerated by the in-browser editor).
// Plain window.BLOG_POSTS array so the author editor can rewrite it safely.
window.BLOG_POSTS = [
  {
    "slug": "agent-remote-private-ai-workspace",
    "title": "Agent Remote: one private window for the agents on my laptops",
    "date": "2026-09-15",
    "year": 2026,
    "tags": ["OpenCode", "Codex", "Android", "Tools"],
    "summary": "A lightweight remote for OpenCode and Codex across computers: searchable chats, subagents, approval requests, private Tailscale access, and reviewed chat handoffs. Download the latest Android APK or Windows/macOS/Linux laptop kit directly.",
    "body": [
      "I wanted a simple way to check the agents running on my different laptops without moving between terminals or trying to remember which machine was waiting for me. Agent Remote brings those conversations into one private workspace, accessible from a browser or a small native Android app. The laptops still do the work; the remote helps me see what is working, what needs input, and where a conversation belongs.",
      "## Download the latest build\n[Download latest Android APK](/remote/agent-remote-latest.apk)\n\n[Download latest laptop ZIP](/remote/agent-remote-laptop.zip)\n\nThese links download the files directly. They always point to the latest build published here. The laptop ZIP includes Windows, macOS, and Linux launchers. Android needs version 9 or newer and an enrolled strong biometric. [Release details and file hashes](/remote/release.json) · [SHA-256 checksums](/remote/checksums.txt).",
      "## A chat menu that remembers the computer\nThe interface has searchable chat history grouped by laptop, with subagents nested under their parent conversation. Working and Needs input give me a view across computers, rather than leaving another laptop hidden behind an old filter. Pending questions and permission requests can be selected individually. Each response goes back to that particular chat on that particular computer.",
      "I can copy a reply, turn an earlier instruction into an editable draft, and switch chats without mixing their unsent text. Editing prepares a new instruction rather than rewriting the agent’s previous transcript. Drafts stay in memory and clear when the remote locks. Tool output stays collapsible so that a conversation remains readable.",
      "## Set up a private connection\nInstall Node.js 24 and Tailscale on the laptop, extract the ZIP into a permanent folder, and open its Start Agent Remote launcher. Choose **This laptop + Tailscale** for the first relay, or **Connect another laptop** to join an existing workspace. The local web wizard guides Tailscale sign-in, private HTTPS, project folders, agent connections, and pairing. Installation and the system VPN approval still happen through the device’s own tools.",
      "On another device, connect Tailscale to the same network and [open the workspace start page](/remote/). An unlocked phone or browser can create a one-time device-link code. **Copy device-link URL** opens the laptop’s linking form with that code already filled in; enter the relay key and verify a passkey to finish. Keep the authorizing device unlocked while linking.",
      "The relay runs on my own laptop, so this setup needs no rented server. Tailscale Personal is free for eligible personal, non-commercial use, and the local integration has no metered Tailscale API charge. Model-provider subscriptions or API usage, internet access, and keeping the laptops powered remain separate.",
      "## Moving a conversation to another laptop\nA handoff transfers reviewed conversation text to a chosen project and agent source on another computer. It does not move the repository, a running process, credentials, or previous tool permissions. I finish or stop the source turn, review the context, and deliver a paused copy. The next instruction starts the continuation on the destination.",
      "There was an important visibility detail to debug with Codex: a paused copy lives in Agent Remote, so it is not yet a native Codex thread. After its first instruction, the continuation is saved with a **Transferred ·** title. The remote shows its native session ID and a copyable Codex resume command. Native Codex needs the same project, OS user, and CODEX_HOME as the destination connector; ChatGPT’s cloud chat list is a separate history.",
      "## Small, private, and tested\nThe app uses the existing React and native Android stack without adding a new runtime dependency for chat navigation. Android uses biometric-gated keys, the browser uses passkeys, and the relay checks computer identity and request boundaries. Offline or stale sources cannot accept control commands. The relay is trusted with the conversation data it forwards; private networking is not a claim of end-to-end encryption through an untrusted server.",
      "The checks cover separate laptop connectors with identical session IDs, subagent questions, request routing, draft isolation, and the signed Android interface. Codex transfer persistence was also checked with the installed Codex app-server and an independent client, using a localhost model fixture instead of paid model calls.",
      "## Updating an existing setup\nInstall the APK over the existing app, and update the relay and the connector files on **every laptop**. Keep the existing configuration, pairing, and private data folders, then restart the launchers. Updating only the phone cannot fix an older laptop connector’s reporting. OpenCode or Codex must be connected through the local agent server that actually owns the session; unrelated terminal processes remain read-only or Not attached.\n\n[Open Agent Remote](/remote/) when you are ready to connect."
    ]
  },
  {
    "slug": "building-a-simple-electron-microscope",
    "title": "Beam Lab: designing a simple electron microscope in the browser",
    "date": "2026-09-11",
    "year": 2026,
    "tags": [
      "Electron microscopy",
      "Electronics",
      "Simulation",
      "ESP32"
    ],
    "summary": "Explore my electron microscope design through an interactive simulator: electron optics, electrical connections, a low-voltage current detector, and a slower 512 × 512 butterfly-wing scan. The hardware remains an unbuilt engineering reference.",
    "body": [
      "I have added [Beam Lab, an interactive electron microscope simulator](/sem/lab/), to this project. It brings the electron source, pumps, lenses, scanning electronics, and detector into one view so that I can examine how their settings fit together. The [original microscope project plan](/sem/) provides the broader context. Beam Lab is a teaching and design tool: its hardware is an unbuilt reference, and the displayed specimens are generated patterns rather than measured micrographs.",
      "## Try the instrument\nTo try it, open the simulator and choose **Start detailed butterfly scan**. The scan progressively reveals a synthetic arrangement of overlapping scales, ridges, and crossribs. Once the frame finishes, it stays visible and can be downloaded as a full-resolution PNG. The specimen selector also includes a calibration pattern, spheres, a diatom, metal grains, a microchip, and fibres, giving different structures to compare under the same settings.",
      "In the microscope view, select a component to inspect it or double-click to zoom in. Change the aperture, accelerating voltage, lens current, or scan amplitude and watch the schematic beam and field overlays respond. Electric fields appear around the anode, aperture, and scan plates; magnetic fields appear around the lens. Colours use fixed strength scales to make changes comparable. Dimensions and electron trajectories are exaggerated for readability. Formula cards expose the current substitutions, derivation, assumptions, and primary references on hover, focus, or tap.",
      "## From specimen to electrical signal\nThe electrical view follows the signal beyond the specimen. The conductive holder sits inside vacuum on an insulating support. A sealed electrical feedthrough connects it to the current amplifier outside the chamber, followed by conditioning, an external ADC, and the ESP32. The [LMC662 detector and wiring guide](/sem/lab/current.html) includes the circuit, connection schedule, calculator, and commissioning notes. The holder needs its intended signal return through the amplifier; an additional direct ground connection would bypass that measurement.",
      "The detector design uses an LMC662 current-to-voltage amplifier and an ADS1115 differential ADC. In the model, incident beam current is reduced by the charge carried away by secondary and backscattered electrons. The remaining current produces the image signal. Its analog electronics use ±5 V, with 3.3 V for the ADC and reference circuitry. Those are project circuit choices; the component capabilities and constraints are documented by [TI for the LMC662](https://www.ti.com/product/LMC662) and [TI for the ADS1115](https://www.ti.com/product/ADS1115).",
      "This avoids an additional detector high-voltage supply, while the electron gun still needs its accelerating supply. It also changes what is measured. An Everhart–Thornley detector collects emitted electrons, accelerates them onto a scintillator, and converts the resulting light through a photomultiplier. JEOL describes a typical scintillator bias of +10 kV in its [ET detector explanation](https://www.jeol.com/words/semterms/20121024.070858.php). The specimen-current design measures net deposited charge, so it cannot be assumed to reproduce the same surface contrast. Earlier ET and silicon BSE models remain available for comparison.",
      "## A slower, more detailed scan\nThe detailed butterfly preset uses **512 × 512 samples over a 140 µm field**, at a 3 kV beam setting. Each pixel allows 5 ms for settling and a 20 ms acquisition window, with two fresh ADS1115 conversions at 128 samples per second. Including row retraces, that produces a modeled hardware frame time of about **109 minutes**, before communication and software overhead. The firmware settings and timing readout agree on that budget.",
      "Waiting nearly two hours would make an interactive demonstration awkward, so the preset uses **500× browser playback**, completing the preview in about 13 seconds. Playback changes only how quickly the modeled pixels appear. It leaves the hardware dwell, ADC settings, exposure calculation, and noise assumptions intact. Reducing playback to 1× reveals the original timing. Taking two readings also does not earn an assumed improvement in noise: drift and correlated interference may survive averaging.",
      "## Positioning is only part of resolution\nFor positioning, the project now selects the dual 16-bit [DAC80502](https://www.ti.com/product/DAC80502). The [scan electronics guide](/sem/lab/scan.html) explains its ESP32 connections and the proposed external scan-driver interface. Finer DAC steps let the controller request more distinct beam positions. They do not shrink the electron spot. In this preset the raster spacing is approximately 274 nm, calculated from 140 µm divided by 511 intervals; that is a sampling distance, not a demonstrated optical resolution.",
      "The scan-program view exposes both the browser trajectory and the ESP32 acquisition sketch. They are separate programs: changing a JavaScript path requires the corresponding C++ trajectory to be updated before hardware use. Beam Lab helps inspect that relationship, including settling, fresh ADC conversions, and blanking. It does not connect to or operate a microscope.",
      "## Public demo and local workspace\nThe public site keeps visitor settings and saved runs in that browser. It cannot modify my project files or launch Codex. The [downloadable local edition](/sem/lab/run-locally.html) additionally supports reading the project BOM and requesting component research through an installed Codex CLI. Both modes keep model assumptions visible; neither can supply measurements for hardware that has not been built.",
      "## What remains to measure\nMy next hardware milestone is to measure the detector's blanked-input noise, leakage, gain, and settling, then establish beam and specimen stability. The current model's extra 5 pA RMS noise floor is an explicit assumption. Conductivity, charging, drift, and beam size still govern whether a real wing feature produces a usable signal. The clearer synthetic frame is useful for studying these tradeoffs, but it does not establish 100 nm butterfly-wing imaging. [Open Beam Lab and explore the detailed scan](/sem/lab/)."
    ]
  },
  {
    "slug": "the-bare-minimums-for-a-civilization",
    "title": "Spectograms",
    "date": "2026-07-12",
    "year": 2026,
    "tags": [
      "physics",
      "tech",
      "modernism"
    ],
    "summary": "In this blog we go through the devices and equipments that shaped our understanding of this world",
    "body": [
      "Let's start with a spectogram."
    ]
  },
  {
    "slug": "education-teaser",
    "title": "Defining education",
    "date": "2026-07-01",
    "year": 2026,
    "tags": [
      "education",
      "self-awareness",
      "environment aware"
    ],
    "summary": "In this blog I will explain how I experienced education and what can be the right way for education for the future generations",
    "body": [
      "Education is ability to produce change in the surrounding by observing all kinds of factors running or comprising it"
    ]
  },
  {
    "slug": "initial-blog-teaser",
    "title": "The way of consuming art",
    "date": "2026-07-01",
    "year": 2026,
    "tags": [
      "Art",
      "Passion"
    ],
    "summary": "Here I explore how I personally consume arts and how it affects me. Especially cinema and music. I might dive into more technical details of it",
    "body": [
      "Consume art in a way that creativity becomes your daily soup."
    ]
  },
  {
    "slug": "a-better-system-to-run-the-world",
    "title": "In Search of a Better System to Run the World",
    "date": "2026-06-30",
    "year": 2026,
    "tags": [
      "systems",
      "motive",
      "first post"
    ],
    "summary": "This is to answer the question of what is the best way to build a better world.",
    "body": [
      "This blog is one of my first actions in the direction of finding a way of creating a system that can build a better world. I got the idea of this when I was having a deep conversation about parallels between India now and India from pre-independence era.",
      "## The first postulate: Evil can never be truly eradicated\nWhat motivated me to understand this. Well in the past 5 years the world has shifted towards the powers which are fundamentally promoting boundaries rather than eliminating them. The civilization has always been through these cycles and this is nothing new. Though for a brief moment in the past 100 years we came together and in the 60's the moment of anti-war was started. The dream was to end the cycle of revenge and establishing ultimate peace. We did a good job at it but the systems we created would have only worked if all the anti-social elements were somehow eradicated. So, my first postulate is that the anti-social elements or as bible says; evil can never be eradicated from this world. So, as you can see where this is going... I will form a mental model by using the structure of math. Which is basically while writing my thoughts I will be establishing postulates and those assuming those postulates to hold in all situations I will come up with the robust system to make the world borderless, just, and a happy place with growth at center can be created.",
      "## The second postulate: Right education is non-negotiable\nI recently visited a city where I saw a weird culture, where people are happy and growing but the government that ruled them through this was a democratically elected communist and socialist parties. Part of the reason why it is such a beautiful city can be the high education, high trust, nearly no classism (though casteism is still a big deal there). Based on the scams of the current government and low trust and high stress environment of the country it is safe to say that democracy just doesn't work where fundamental needs of people are not fulfilled. So, let me first define what education is fundamentally. Education is the ability of a person to get observation from surrounding, articulate it and the ability to apply either or both of creativity and logical reasoning and generate outcomes for the society. So, is the guy who has a PhD in economics but talks about being an upper class citizen in this world an educated person? Nope, he is literate but not educated. Education is very comprehensive and must contain deep social interactions in order to be complete. (On the side note, Education about your own mind can help you avoid mental problems later and education does include social interactions, will explain more about this in another blog). So, the point is the education system currently focuses on grades, math, english, science, etc. But this is just broken. Because all this can be done with machines but being human is a lesson that is often skipped in the education system. To make children realise that a system can be changed according to their needs and they have a power to do so, we create a stronger world.",
      "## The third postulate: Next generation are the torch bearers and the new system has to make sure they know what power they hold and teach them responsibility with humanity at its center",
      "One of the things I have personally noticed is that when the cycle of rotten system is exposed, there is a rise of people who try to make a new system which replaced the former system. But this process takes time of at least two generations. Eg. Revolt of 1857 yielded us the freedom in 1947. Why a new system? So, there are two quotes which are relevant to this by indian freedom fighters bhagat singh and subhash chandra bose.\n1. \"Inquilab Zindabad\"; translation: Long live the revolution. My interpretation: revolution must never die.\n2. \"if you refuse to participate in politics, you end up being governed by your inferiors\";",
      "So, this brings me to the fourth postulate; No man-made system can be perfect.",
      "## The fourth postulate: No man made system can be perfect.",
      "This brings us to the next point i.e. what I observed in successful and failed revolutions.\nFirst step and the longest step in the revolution is called creating a leverage. Leverage against state, army, economy, and legitimacy (basically media). Why is it the longest? because creating a leverage isn't child's play, it requires all of the following; a strong leadership heading the leverage created in all the sectors, economy, sciences, politics (well all the leaders have to be vocally political and strong). These strong leaders might have to infiltrate like the norm but have to gradually become vocal. This will come at a cost of regime improsining them indefinitely or even worse sentence to death. But, remember revolution is done across generations not in 2 years; callback to 1857.\nHow do one create leverage? For that one must be in the system and accel their way to the top, this will take years of education, hardwork, and sacrifices. But once you reach at top, one have assemble a small focused group that are aligned with the ideas from top to bottom.",
      "N important symbols needed to influence people:\n1. A Gandhi: A leader who sets and example by living the way we imagine the world to be\n2. A General (Bose): A leader who will do whatever it takes to get the power from the oppressors and is ready to implement a new system\n3. The Innovator (Bhabha): A visionary who looks the need of the world 100 years later and puts systems in place for the same\n4. A leader: A person or people, who listens to all of the 3 above, forms the idea of the new world and has guts to take the blame and make ammends to the new established system.",
      "Yes a leader can be plural, we are not assuming that one leader is enough to govern the world. What I imagine as the leaders of this world is a responsibility taken up by the people who are at the peak of their fields and they lead that particular field and make sure the progress is exponential in those fields. For this ground level knowledge has to be mandatory for the leadership. A leader must understand how their surroundings are, how people with lower income and higher income live together, what are different blockers their people face. And make sure to build bridges instead of walls to just vanish the gap in between people. The gap of casteism, the gap of racism, the gap of classism, and many more.",
      "observe the pattern I highlight through the examples. It will become obvious why successful revolutions succeeded.\nexamples of failed revolutions:\n1. 1919 german revolution: \n| Needed for success\t| Situation in Germany (1919)|\n| -------- | -------- |\n| Broad public support\t| ❌ Limited mainly to radical workers in some cities|\n| Military defections\t| ❌ Government retained armed support through the Freikorps|\n| Unified left\t| ❌ Deep split between the SPD and KPD|\n| National coordination\t| ❌ Mostly centered in Berlin|\n| Administrative plan\t| ❌ No clear path to governing Germany after victory|\n2. Bahrain revolution 2011: The army and key institutions were loyal to the existing rotted system, they are also the citizens and they must be realised what is right and what's wrong. The movement was only localised to the capital and nothing else, which is really really concerning",
      "2. \nComing up: \n1. how ai is a fundamental right\n2. mathematical structure of revolution\n3. calculation for the funds needed over the years to perform a successful revolution\n4. how intervention of foreign powers must be taken into account in all possible ways and make leverage out of it"
    ]
  }
];
