// posts.js — blog posts data (regenerated by the in-browser editor).
// Plain `window.BLOG_POSTS = [...]` so it can be rewritten + committed safely.
window.BLOG_POSTS = [
  {
    "slug": "a-better-system-to-run-the-world",
    "title": "In Search of a Better System to Run the World",
    "date": "2026-06-30",
    "year": 2026,
    "tags": [
      "systems",
      "motive",
      "first post"
    ],
    "summary": "This is to answer the question of what is the best way to build a better world.",
    "body": [
      "This blog is one of my first actions in the direction of finding a way of creating a system that can build a better world. I got the idea of this when I was having a deep conversation about parallels between India now and India from pre-independence era."
    ]
  }
];
