// posts.js — blog posts data (regenerated by the in-browser editor).
// Plain `window.BLOG_POSTS = [...]` so it can be rewritten + committed safely.
window.BLOG_POSTS = [
  {
    "slug": "a-better-system-to-run-the-world",
    "title": "In Search of a Better System to Run the World",
    "date": "2026-06-30",
    "year": 2026,
    "tags": [
      "systems",
      "motive",
      "first post"
    ],
    "summary": "This is to answer the question of what is the best way to build a better world.",
    "body": [
      "This blog is one of my first actions in the direction of finding a way of creating a system that can build a better world. I got the idea of this when I was having a deep conversation about parallels between India now and India from pre-independence era.",
      "## The first postulate: Evil can never be truly eradicated\nWhat motivated me to understand this. Well in the past 5 years the world has shifted towards the powers which are fundamentally promoting boundaries rather than eliminating them. The civilization has always been through these cycles and this is nothing new. Though for a brief moment in the past 100 years we came together and in the 60's the moment of anti-war was started. The dream was to end the cycle of revenge and establishing ultimate peace. We did a good job at it but the systems we created would have only worked if all the anti-social elements were somehow eradicated. So, my first postulate is that the anti-social elements or as bible says; evil can never be eradicated from this world. So, as you can see where this is going... I will form a mental model by using the structure of math. Which is basically while writing my thoughts I will be establishing postulates and those assuming those postulates to hold in all situations I will come up with the robust system to make the world borderless, just, and a happy place with growth at center can be created.",
      "## The second postulate: Right education is non-negotiable\nI recently visited a city where I saw a weird culture, where people are happy and growing but the government that ruled them through this was a democratically elected communist and socialist parties. Part of the reason why it is such a beautiful city can be the high education, high trust, nearly no classism (though casteism is still a big deal there). Based on the scams of the current government and low trust and high stress environment of the country it is safe to say that democracy just doesn't work where fundamental needs of people are not fulfilled. So, let me first define what education is fundamentally. Education is the ability of a person to get observation from surrounding, articulate it and the ability to apply either or both of creativity and logical reasoning and generate outcomes for the society. So, is the guy who has a PhD in economics but talks about being an upper class citizen in this world an educated person? Nope, he is literate but not educated. Education is very comprehensive and must contain deep social interactions in order to be complete. (On the side note, Education about your own mind can help you avoid mental problems later and education does include social interactions, will explain more about this in another blog). So, the point is the education system currently focuses on grades, math, english, science, etc. But this is just broken. Because all this can be done with machines but being human is a lesson that is often skipped in the education system. To make children realise that a system can be changed according to their needs and they have a power to do so, we create a stronger world.",
      "## The third postulate: Next generation are the torch bearers and the new system has to make sure they know what power they hold and teach them responsibility with humanity at its center",
      "One of the things I have personally noticed is that when the cycle of rotten system is exposed, there is a rise of people who try to make a new system which replaced the former system. But this process takes time of at least two generations. Eg. Revolt of 1857 yielded us the freedom in 1947. Why a new system? So, there are two quotes which are relevant to this by indian freedom fighters bhagat singh and subhash chandra bose.\n1. \"Inquilab Zindabad\"; translation: Long live the revolution. My interpretation: revolution must never die.\n2. \"if you refuse to participate in politics, you end up being governed by your inferiors\";",
      "So, this brings me to the fourth postulate; No man-made system can be perfect.",
      "## The fourth postulate: No man made system can be perfect.",
      "This brings us to the next point i.e. what I observed in successful and failed revolutions"
    ]
  }
];
