import {request} from './workspace.js';
import {SOURCES,PMT_WIRING,HV_CONNECTIONS,PARTS,checkDetector} from './detector-reference.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const link=id=>`<a class="source" href="${SOURCES[id].url}" target="_blank" rel="noopener noreferrer">${SOURCES[id].title} ↗</a>`;
$$('[data-source]').forEach(el=>{el.innerHTML=link(el.dataset.source);});
$('#wire-grid').innerHTML=PMT_WIRING.map(w=>`<article class="wire-card"><h3><i style="--lead:${w.color}"></i>${w.wire}</h3><strong>${w.function} → ${w.to}</strong><p>${w.note}</p></article>`).join('');
$('#hv-table').innerHTML=HV_CONNECTIONS.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('');
$('#parts-table').innerHTML=PARTS.map(([role,part,status,source])=>`<tr><td>${role}</td><td>${part}</td><td>${status}${link(source)}</td></tr>`).join('');
const steps=[
  ['Define the detector assembly','Get a drawing for the coated scintillator, cage, light guide, vacuum seal and HV contact. Match the optical exit to the PMT’s 8 mm active area. Request a voltage/pressure rating and installation procedure.','A complete mechanical/electrical interface drawing; no guessed coating contact or feedthrough pinout.','YAP:Ce at 370 nm is spectrally compatible with the H10722-110 range. This does not certify optical collection efficiency.'],
  ['Check the PMT electronics on the bench','Keep the scintillator HV disconnected. Cover the PMT window. Verify +5 V/red, −5 V/green and 0 V/black before connection. Set an external control source to +0.5 V/white; insulate blue. Use the scope’s high-impedance DC input on the signal coax.','A stable dark baseline with correct rail polarities. Keep bright room light out of the operating PMT.','The manufacturer specifies up to 10 seconds to settle after a gain-control change. Measure gain only after it settles.'],
  ['Verify light-to-voltage response','Use a very weak, adjustable blue/near-UV light source through the intended optical coupling. Start at the lowest specified gain setting and increase illumination slowly. Record dark offset, gain and the onset of clipping.','A repeatable voltage response with headroom. An initial target around 0.2–2 V is an engineering starting point, not a datasheet calibration.','A >4 V ideal demand is not a valid linear prediction for the standard module. No external TIA is required for H10722.'],
  ['Integrate vacuum and HV hardware','Mount the rated scintillator/cage assembly and seal the optical boundary. Keep the PMT in air. Verify chamber PE, separate returns, pressure-qualified feedthroughs, HV inhibit and discharge provision against the selected manuals.','Leak-tight optics and a reviewed HV wiring/insulation assembly. HV stays inhibited through pumping and venting.','Use qualified vacuum/HV commissioning support. No generic spacing or discharge delay on this page substitutes for the assembly ratings.'],
  ['Commission the detector bias and beam','At the assembly-approved vacuum, follow its HV ramp procedure with the primary beam blanked. Check dark signal and HV behavior, then introduce a low-current beam and adjust collector bias and PMT gain within the actual ratings.','Secondary-electron contrast without amplifier clipping or unexpected background. Compare beam-blanked and beam-on readings.','Scintillator bias controls electron landing energy; Vcont controls PMT sensitivity. Do not change one as if it were the other.'],
  ['Calibrate acquisition, then scan','Start with ≥100 µs pixel dwell as a conservative experiment for this 20 kHz module. Measure scan settling. Record adequate-rate ADC samples and filter/average into pixels. For shutdown, blank the beam, inhibit detector HV, verify discharge and follow pump/vent procedures.','A repeatable dark-subtracted image with known scale, headroom and measured timing.','The current ESP32 firmware uses an internal ADC. ADS8681 is a candidate requiring separate SPI integration; do not wire a 4 V output directly to the existing ADC input.'],
];
$('#steps').innerHTML=steps.map(([title,body,expected,note],i)=>`<article class="step"><div class="step-heading"><span>0${i+1}</span><h3>${title}</h3></div><p>${body}</p><p class="expected"><strong>Ready to advance:</strong> ${expected}</p><small>${note}</small></article>`).join('');
const notes={
  all:['One detector, three separate functions','Scintillator positive HV accelerates secondary electrons. The collector attracts them. The PMT module receives only low-voltage power and light.','et',['light','scintillator','collector']],
  optical:['Electrons become photons','A conductive scintillator coating receives the HV contact. The light guide carries light through the sealed boundary. It does not conduct that HV to the PMT.','et',['light']],
  collector:['Collector cage: separate bias','The example cage is at +250 V relative to chamber reference, insulated from both ground and the +10 kV coating. Exact bias and contacts come from the assembly drawing.','et',['collector']],
  scintillator:['Scintillator: separate positive HV output','Connect its specified conductive contact through a voltage-rated cable and vacuum feedthrough. Return to the defined chamber reference. +10 kV is an example, not a universal requirement.','et',['scintillator']],
  module:['H10722-110: a specific module proposal','Its internal supply powers the tube, and its internal amplifier provides a voltage output. No separate 1.1 kV PMT supply or external TIA connects to this module. The module must remain in air.','pmt',['positive','negative','return','control','signal','light']],
  power:['Bipolar power means three conductors','Red is +5 V, green is −5 V, and black is the common midpoint. Verify both voltages relative to black. Green is not another ground lead.','pmt',['positive','negative','return']],
  control:['Gain programming: white input, blue output','Apply +0.5 to +1.1 V to white relative to black. With an external programming source, leave the blue 1.2 V reference electrically insulated. No direct 3.3 V GPIO drive.','pmt',['control','return']],
  signal:['Coax carries a voltage signal','Start with a 1 MΩ, DC-coupled scope input. The standard amplifier converts 1 µA to about 1 V, up to the specified output swing. A high-impedance ADC with a suitable range can follow.','product',['signal']],
};
function select(id){const [title,body,source,nets]=notes[id]||notes.all;$('#map-note').innerHTML=`<strong>${title}</strong>${body} ${link(source)}`;$$('[data-select]').forEach(el=>el.classList.toggle('selected',el.dataset.select===id));$$('[data-net]').forEach(el=>el.classList.toggle('active',nets.includes(el.dataset.net)));}
$$('[data-select]').forEach(el=>{el.addEventListener('click',()=>select(el.dataset.select));el.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select(el.dataset.select);}});});
const svg=$('#connection-map'),regions={all:[0,0,1100,535],vacuum:[0,35,450,495],module:[480,105,595,420]};let bounds=[...regions.all],drag=null;
function view(){svg.setAttribute('viewBox',bounds.join(' '));['x','y','width','height'].forEach((key,i)=>$('#clip-rect').setAttribute(key,bounds[i]));}
$$('[data-focus]').forEach(btn=>btn.addEventListener('click',()=>{bounds=[...regions[btn.dataset.focus]];view();$$('[data-focus]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',b===btn);});}));
function zoom(factor){const width=Math.max(240,Math.min(1450,bounds[2]*factor)),ratio=width/bounds[2],height=bounds[3]*ratio;bounds=[bounds[0]+(bounds[2]-width)/2,bounds[1]+(bounds[3]-height)/2,width,height];view();}
$('#zoom-in').onclick=()=>zoom(.8);$('#zoom-out').onclick=()=>zoom(1.25);
svg.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:.9);},{passive:false});
svg.addEventListener('pointerdown',e=>{if(e.button===0&&!e.target.closest('[data-select]')){drag={x:e.clientX,y:e.clientY,b:[...bounds]};svg.setPointerCapture(e.pointerId);}});
svg.addEventListener('pointermove',e=>{if(!drag)return;const scale=Math.min(svg.clientWidth/drag.b[2],svg.clientHeight/drag.b[3]);bounds=[drag.b[0]-(e.clientX-drag.x)/scale,drag.b[1]-(e.clientY-drag.y)/scale,...drag.b.slice(2)];view();});
svg.addEventListener('pointerup',()=>{drag=null;});svg.addEventListener('pointercancel',()=>{drag=null;});select('all');
const query=new URLSearchParams(location.search);
for(const [param,id,min,max] of [['current','current',0,1e6],['dwell','dwell',1,1e6]]){const value=Number(query.get(param));if(query.has(param)&&Number.isFinite(value)&&value>=min&&value<=max)$('#'+id).value=value;}
if(query.has('current'))$('#check-origin').textContent='COPIED GENERIC MODEL INPUTS · NOT LIVE';
function update(){const ids=['current','dwell','scintillator','control'];const invalid=ids.some(id=>!$('#'+id).validity.valid||$('#'+id).value==='');$('#input-warning').hidden=!invalid;if(invalid){$('#input-warning').textContent='Enter valid values in all four fields. The results below retain the last valid calculation.';return;}const d=checkDetector({currentuA:+$('#current').value,dwellUs:+$('#dwell').value,scintillatorkV:+$('#scintillator').value,controlV:+$('#control').value});
  $('#output-value').textContent=`${d.idealOutputV.toFixed(2)} V`;$('#settling-value').textContent=`${d.settle1PercentUs.toFixed(2)} µs`;$('#energy-value').textContent=`${d.landingEnergykeV.toFixed(1)} keV`;
  $('#headroom-message').textContent=d.warning;$('#headroom-message').classList.toggle('bad',d.atOutputLimit);
  $('#control-message').textContent=d.controlValid?'Vcont is within the specified adjustment range. No internal HV or gain is inferred from this setting.':'Vcont is outside the specified 0.5–1.1 V range. Do not apply this value to the module.';$('#control-message').classList.toggle('bad',!d.controlValid);
  $('#timing-message').textContent=d.slowEnoughForStep?'Dwell exceeds the simple 1% settling estimate. This alone does not validate scan timing, ADC acquisition or alias rejection.':'Dwell is shorter than the simple 1% settling estimate. Increase dwell and measure the complete scan-to-signal response.';
  $('#signal-fill').style.width=`${Math.min(100,d.idealOutputV/4*100)}%`;$('#signal-fill').style.background=d.atOutputLimit?'#bd8250':'#549b82';$('#formula-output').textContent=`${$('#current').value} µA × 1 V/µA = ${d.idealOutputV.toFixed(2)} V demanded`;$('#formula-energy').textContent=`${$('#scintillator').value} kV → ${d.landingEnergykeV.toFixed(1)} keV`;
}
$$('.control-panel input').forEach(input=>input.addEventListener('input',update));update();
$$('.math-card').forEach(el=>{let pinned=false;el.querySelector('summary').addEventListener('click',e=>{e.preventDefault();pinned=!pinned;el.open=pinned;});el.addEventListener('pointerenter',()=>{el.open=true;});el.addEventListener('pointerleave',()=>{if(!pinned)el.open=false;});el.addEventListener('focusin',()=>{el.open=true;});el.addEventListener('focusout',e=>{if(!pinned&&!el.contains(e.relatedTarget))el.open=false;});});
request('/api/bom').then(bom=>{const part=bom.components?.find(x=>x.id==='detector');$('#bom-status').textContent=part?`Current BOM: ${part.name}${part.mpn?' · '+part.mpn:''}. Status: ${part.status}. This reference does not select or modify that part.`:'No detector mapping found. The proposal has not changed the BOM.';}).catch(()=>{$('#bom-status').textContent='BOM could not be read. This research page still works; its proposal has not been applied.';});
