#!/usr/bin/env node
// fetch-pets.mjs — vendor PetDex pets INTO this repo so the site never depends
// on petdex.dev at runtime (blocker-proof, offline-proof, works over file://).
//
// It resolves each requested pet from the public PetDex manifest, downloads its
// spritesheet to  pets/<slug>/sprite.webp , and regenerates  pets/manifest.js
// (a classic script that sets window.PETS). The site loads only those local files.
//
// Usage:
//   node scripts/fetch-pets.mjs boba dalek pixel-panda        # add these pets
//   node scripts/fetch-pets.mjs --curated                     # add all curated pets
//   node scripts/fetch-pets.mjs --list boba,nukey,scoop       # comma form
//   node scripts/fetch-pets.mjs --remove homelander           # drop a pet
//   node scripts/fetch-pets.mjs --force boba                  # re-download
//   node scripts/fetch-pets.mjs                               # just rebuild manifest.js
//
// Names may be slugs, display names, or petdex.dev/pets/<slug> URLs.

import { mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const PETS_DIR = path.join(ROOT, "pets");
const MANIFEST_JS = path.join(PETS_DIR, "manifest.js");
const MANIFEST_URLS = [
  "https://assets.petdex.dev/manifests/petdex-v1.json",
  "https://petdex.dev/api/manifest",
];

function slugify(s) {
  return String(s || "").normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}
function asSlug(token) {
  token = String(token || "").trim();
  const m = token.match(/petdex\.dev\/(?:[a-z]{2}\/)?pets\/([^/?#]+)/i);
  if (m) return slugify(m[1]);
  return slugify(token);
}
function human(bytes) {
  return bytes > 1e6 ? (bytes / 1e6).toFixed(1) + " MB" : Math.round(bytes / 1024) + " KB";
}

async function getJSON(url) {
  const r = await fetch(url, { redirect: "follow" });
  if (!r.ok) throw new Error("HTTP " + r.status + " for " + url);
  return r.json();
}
async function fetchManifest() {
  let err;
  for (const u of MANIFEST_URLS) {
    try { const j = await getJSON(u); return (j && j.pets) || j; }
    catch (e) { err = e; }
  }
  throw err || new Error("manifest unreachable");
}

// read existing window.PETS out of pets/manifest.js (our own generated format)
async function readExisting() {
  if (!existsSync(MANIFEST_JS)) return {};
  try {
    const txt = await readFile(MANIFEST_JS, "utf8");
    const m = txt.match(/window\.PETS\s*=\s*(\{[\s\S]*\});?\s*$/);
    if (!m) return {};
    const obj = JSON.parse(m[1]);
    const out = {};
    for (const p of obj.pets || []) out[p.slug] = p;
    return out;
  } catch (e) { return {}; }
}

async function writeManifest(petsMap) {
  const pets = Object.values(petsMap).sort((a, b) => a.slug.localeCompare(b.slug));
  const payload = { version: 1, generatedAt: new Date().toISOString(), pets };
  const banner =
    "// pets/manifest.js — GENERATED by scripts/fetch-pets.mjs. Do not edit by hand.\n" +
    "// Vendored PetDex pets served locally (blocker-proof). Regenerate with:\n" +
    "//   node scripts/fetch-pets.mjs <name...>\n";
  await writeFile(MANIFEST_JS, banner + "window.PETS = " + JSON.stringify(payload, null, 2) + ";\n");
  return pets;
}

async function main() {
  const argv = process.argv.slice(2);
  const flags = new Set(argv.filter((a) => a.startsWith("--")));
  const consumed = new Set();               // indices used as flag values, not names
  function valueAfter(flag) { const i = argv.indexOf(flag); if (i === -1) return ""; consumed.add(i); consumed.add(i + 1); return argv[i + 1] || ""; }
  const listVal = valueAfter("--list");
  const removeVal = valueAfter("--remove");
  let names = argv.filter((a, i) => !a.startsWith("--") && !consumed.has(i));
  if (listVal) names = names.concat(listVal.split(","));
  const removals = removeVal ? removeVal.split(",").map(asSlug).filter(Boolean) : [];
  const force = flags.has("--force");

  await mkdir(PETS_DIR, { recursive: true });
  const existing = await readExisting();

  // handle removals
  for (const slug of removals) {
    delete existing[slug];
    await rm(path.join(PETS_DIR, slug), { recursive: true, force: true });
    console.log("removed " + slug);
  }

  const wanted = names.map(asSlug).filter(Boolean);
  if (!wanted.length && !flags.has("--curated") && !removals.length) {
    console.log("rebuilding manifest.js from " + Object.keys(existing).length + " existing pets\u2026");
    const pets = await writeManifest(existing);
    console.log("wrote pets/manifest.js (" + pets.length + " pets)");
    return;
  }

  console.log("fetching PetDex manifest\u2026");
  const remote = await fetchManifest();
  const bySlug = new Map(), byName = new Map();
  for (const p of remote) {
    if (!p.slug || !(p.spritesheetUrl || p.url)) continue;
    bySlug.set(p.slug, p);
    const a = slugify(p.displayName || "");
    if (a && !byName.has(a)) byName.set(a, p);
  }
  console.log("  " + remote.length + " pets in gallery");

  let targets = wanted.slice();
  if (flags.has("--curated")) {
    for (const p of remote) if (/\/curated\//.test(p.spritesheetUrl || "")) targets.push(p.slug);
  }
  targets = [...new Set(targets)];

  let ok = 0, skip = 0, fail = 0, totalBytes = 0;
  for (const name of targets) {
    const p = bySlug.get(name) || byName.get(name);
    if (!p) { console.log("  ! not found: " + name); fail++; continue; }
    const slug = p.slug;
    const dir = path.join(PETS_DIR, slug);
    const file = path.join(dir, "sprite.webp");
    const rel = "pets/" + slug + "/sprite.webp";
    if (existsSync(file) && !force) {
      existing[slug] = { slug, name: p.displayName || slug, by: p.submittedBy || "", file: rel };
      console.log("  = " + slug + " (already vendored)");
      skip++; continue;
    }
    try {
      const url = p.spritesheetUrl || p.url;
      const r = await fetch(url, { redirect: "follow" });
      if (!r.ok) throw new Error("HTTP " + r.status);
      const buf = Buffer.from(await r.arrayBuffer());
      await mkdir(dir, { recursive: true });
      await writeFile(file, buf);
      totalBytes += buf.length;
      existing[slug] = { slug, name: p.displayName || slug, by: p.submittedBy || "", file: rel };
      console.log("  + " + slug + "  (" + human(buf.length) + ")  " + (p.displayName || ""));
      ok++;
    } catch (e) { console.log("  ! failed " + slug + ": " + e.message); fail++; }
  }

  const pets = await writeManifest(existing);
  console.log("\ndownloaded " + ok + ", skipped " + skip + ", failed " + fail +
    " \u2014 " + human(totalBytes) + " added");
  console.log("manifest now has " + pets.length + " pets \u2192 pets/manifest.js");
  if (fail) process.exitCode = 1;
}

main().catch((e) => { console.error("fatal:", e.message); process.exit(1); });
