// pets/manifest.js — GENERATED by scripts/fetch-pets.mjs. Do not edit by hand.
// Vendored PetDex pets served locally (blocker-proof). Regenerate with:
//   node scripts/fetch-pets.mjs <name...>
window.PETS = {
  "version": 1,
  "generatedAt": "2026-07-03T06:40:59.811Z",
  "pets": [
    {
      "slug": "boba",
      "name": "Boba",
      "by": "railly",
      "file": "pets/boba/sprite.webp"
    },
    {
      "slug": "dalek",
      "name": "Dalek（戴立克）",
      "by": "hanjin714",
      "file": "pets/dalek/sprite.webp"
    },
    {
      "slug": "homelander",
      "name": "Homelander",
      "by": "Serhat",
      "file": "pets/homelander/sprite.webp"
    },
    {
      "slug": "nukey",
      "name": "Nukey",
      "by": "railly",
      "file": "pets/nukey/sprite.webp"
    },
    {
      "slug": "pixel-panda",
      "name": "Pixel Panda",
      "by": "railly",
      "file": "pets/pixel-panda/sprite.webp"
    },
    {
      "slug": "scoop",
      "name": "Scoop",
      "by": "railly",
      "file": "pets/scoop/sprite.webp"
    }
  ]
};
