// pets/manifest.js — GENERATED by scripts/fetch-pets.mjs. Do not edit by hand.
// Vendored PetDex pets served locally (blocker-proof). Regenerate with:
//   node scripts/fetch-pets.mjs <name...>
window.PETS = {
  "version": 1,
  "generatedAt": "2026-07-03T07:32:31.917Z",
  "pets": [
    {
      "slug": "dobby-2",
      "name": "Dobby",
      "by": "danblock97",
      "file": "pets/dobby-2/sprite.webp"
    },
    {
      "slug": "homelander",
      "name": "Homelander",
      "by": "Serhat",
      "file": "pets/homelander/sprite.webp"
    },
    {
      "slug": "noir-webling",
      "name": "Noir Webling",
      "by": "railly",
      "file": "pets/noir-webling/sprite.webp"
    },
    {
      "slug": "nukey",
      "name": "Nukey",
      "by": "railly",
      "file": "pets/nukey/sprite.webp"
    },
    {
      "slug": "pixel-panda",
      "name": "Pixel Panda",
      "by": "railly",
      "file": "pets/pixel-panda/sprite.webp"
    },
    {
      "slug": "tiko",
      "name": "Tiko",
      "by": "huigegood",
      "file": "pets/tiko/sprite.webp"
    }
  ]
};
